### ISSUE TITLE
if i Use body_text & body_html & and have no attachment and use UTF-8 i have message 

### ISSUE THREAD

**Issue by vixivixi** [stlewis/Mail#2]
--PHP-mixed-c71e9898e2ff03c758cd9ad6d8f0fa39
Content-Type: multipart/alternative; boundary="PHP-alt-c71e9898e2ff03c758cd9ad6d8f0fa39"

--PHP-alt-c71e9898e2ff03c758cd9ad6d8f0fa39
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 8bit

ÐžÐ¿Ð¸ÑÐ°Ð½Ð¸Ðµ - Ð˜Ð•Ð³Ð¾Ñ‚Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ Ð¿Ð°ÑÐ¿Ð¾Ñ€Ñ‚Ð° Ñ„Ð°ÑÐ°Ð´Ð° 

--PHP-alt-c71e9898e2ff03c758cd9ad6d8f0fa39
Content-Type: text/html; charset="UTF-8  "
Content-Transfer-Encoding: 8bit

<div>Ð•Ð³Ð¾Ñ‚Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ Ð¿Ð°ÑÐ¿Ð¾Ñ€Ñ‚Ð° Ñ„Ð°ÑÐ°Ð´Ð° 

--PHP-alt-c71e9898e2ff03c758cd9ad6d8f0fa39--

but if i make attachment it all will be ok!

**Comment by stlewis** [comment]
I believe this was probably addressed in #6
