### ISSUE TITLE
I have more than one CC,how can I do?

### ISSUE THREAD

**Issue by guojun1992** [stlewis/Mail#3]
$mail->add_header("Cc: someone_else@example.com");

**Comment by stlewis** [comment]
The header can generally take a comma-delimited string, ie:

`$mail->add_header("Cc: someone@example.com,someone_else@example.com")`

**Comment by guojun1992** [comment]
thanks  for your help~

**Comment by JinAirsOs** [comment]
When i use it to send email,the subject and receiver show twice,is it your program bug? how can i fix it ..thank you~
i mean that the email i received is like this.
subject:subjectsubject
receiver: test@example.com;test@example.com
but i only write it once in program!

**Comment by guojun1992** [comment]
@JinAirsOs I have the same problem,but I do not care,though receiver  show twice,I can recieve the email,  I use it into a reoprt email system,not to users

**Comment by JinAirsOs** [comment]
@guojun1992 After carefully read the code,i have fix it.Things is easy,he make mistakes at $to and $subject.mail function add header $to and $suject and he add that header too.So just comment it in set_default_headers() like this.It will looks good!
private function set_default_headers(){
      $this->headers[] = 'MIME-Version: 1.0';
      $this->headers[] = "From: {$this->from}";
      //$this->headers[] = "To: {$this->to}";
      //$this->headers[] = "Subject: {$this->subject}";
      $this->headers[] = "Content-type: multipart/mixed; boundary=\"PHP-mixed-{$this->boundary_hash}\"";
    }

**Comment by guojun1992** [comment]
@JinAirsOs good job

**Comment by stlewis** [comment]
@JinAirsOs Thanks for looking in to this, it's been a long time since I've been able to focus on this library.  Any chance I could get you to submit a pull request with the changes?

Thanks!

**Comment by JinAirsOs** [comment]
I have fix the bug and make some changes to that it more usefull,utf-8
encode looks more good i think ,for coutries that don't use english can use
this tool too!and fix a warning that you use the date() to make
boundary_hash but don't set timezone,so i set it in the construct to fix it
.
