### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by JinAirsOs** [stlewis/Mail#5]
When i use it to send email,the subject and receiver show twice,is it your program bug? how can i fix it ..thank you~
i mean that the email i received is like this.
subject:subjectsubject
receiver: test@example.com;test@example.com
but i only write it once in program!

**Comment by JinAirsOs** [comment]
After carefully read the code,i have fix it.Things is easy,he make mistakes at $to and $subject.mail function add header $to and $suject and he add that header too.So just comment it in set_default_headers() like this.It will looks good!
private function set_default_headers(){
$this->headers[] = 'MIME-Version: 1.0';
$this->headers[] = "From: {$this->from}";
//$this->headers[] = "To: {$this->to}";
//$this->headers[] = "Subject: {$this->subject}";
$this->headers[] = "Content-type: multipart/mixed; boundary=\"PHP-mixed-{$this->boundary_hash}\"";
}

**Comment by stlewis** [comment]
@JinAirsOs Feel free to submit a pull request with this fix, I'll merge it in.

Thanks!
