### ISSUE TITLE
Not able to send html data mail

### ISSUE THREAD

**Issue by jsroyal** [stlewis/Mail#7]
Help wanted!.

I created HTML form and all data want to send to mail but not able to get it.
![screenshot from 2016-12-21 12 03 13](https://cloud.githubusercontent.com/assets/10773353/21416801/ce92635e-c83b-11e6-948c-a6cd88310b57.png)
So how do I approach it? please help?
I go through you repo but not able implement.

**Comment by stlewis** [comment]
I feel terrible about the fact that I never saw this until now and you probably aren't in a position where you need my help anymore...My apologies on that!

With that said, feel free to re-open this if you still need help!
