### ISSUE TITLE
Not able to send attachments

### ISSUE THREAD

**Issue by luzan** [stlewis/Mail#9]
As stated on Docs, I did `$mail->add_attachments($_FILES['myFile']);` . Buy I am getting this error.
> Warning:  basename() expects parameter 1 to be string, array given
> Warning:  file_get_contents() expects parameter 1 to be a valid path, array given

Do I have to upload file on the server before sending email?

**Comment by Committing** [comment]
You need to print_r(); your $_FILES and find the array value that has the direct path...

**Comment by stlewis** [comment]
@Committing is right -- the `add_attachment` method expects a direct file path. To be explicit, you can retrieve this direct path via the following:

`$path_to_file = $_FILES['myFile']['tmp_name']`

Having done so:

`
$path_to_file = $_FILES['myFile']['tmp_name']
$mail->add_attachment($path_to_file);
`

The above should work.
